# Generated by Django 2.2.7 on 2019-11-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblAccessorySpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_accessory_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblBrands',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('activate', models.TextField()),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=255, null=True)),
                ('google_plus_link', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblBusinessSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_in_price', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_business_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCars',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('engine', models.IntegerField()),
                ('features', models.TextField(blank=True, null=True)),
                ('fuel', models.CharField(blank=True, max_length=255, null=True)),
                ('make_year', models.IntegerField()),
                ('price', models.FloatField()),
                ('transmission', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_cars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCarSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('engine', models.CharField(blank=True, max_length=255, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('fuel', models.CharField(blank=True, max_length=255, null=True)),
                ('kilometers', models.IntegerField()),
                ('make_year', models.IntegerField()),
                ('transmission', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_car_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCategories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblClothingSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_clothing_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCommonSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('used_for', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_common_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCustomer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('verified', models.IntegerField()),
                ('city_name', models.CharField(max_length=255)),
                ('area_location', models.CharField(blank=True, max_length=255, null=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_area', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_charges', models.CharField(blank=True, max_length=255, null=True)),
                ('home_delivery', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblHandsetSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_camera', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu_core', models.CharField(blank=True, max_length=255, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('front_camera', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_storage', models.CharField(blank=True, max_length=255, null=True)),
                ('ownership', models.CharField(blank=True, max_length=255, null=True)),
                ('ram', models.CharField(blank=True, max_length=255, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=255, null=True)),
                ('sim_slot', models.CharField(blank=True, max_length=255, null=True)),
                ('smartphone_os', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_handset_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblHousings',
            fields=[
                ('housing_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateField(blank=True, null=True)),
                ('appliances', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.IntegerField()),
                ('available', models.CharField(blank=True, max_length=255, null=True)),
                ('bathroom', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('cooling', models.CharField(blank=True, max_length=255, null=True)),
                ('dates', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('flooring', models.CharField(blank=True, max_length=255, null=True)),
                ('heating', models.CharField(blank=True, max_length=255, null=True)),
                ('housing_name', models.CharField(blank=True, max_length=255, null=True)),
                ('laundry', models.CharField(blank=True, max_length=255, null=True)),
                ('others', models.CharField(blank=True, max_length=255, null=True)),
                ('parking', models.CharField(blank=True, max_length=255, null=True)),
                ('pets', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField()),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('rent_per_sqft', models.FloatField()),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_floor', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_housings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLaptopSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery', models.CharField(blank=True, max_length=255, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('hdd', models.CharField(blank=True, max_length=255, null=True)),
                ('processor', models.CharField(blank=True, max_length=255, null=True)),
                ('processor_generation', models.CharField(blank=True, max_length=255, null=True)),
                ('ram', models.IntegerField()),
                ('screen_size', models.IntegerField()),
                ('screen_type', models.CharField(blank=True, max_length=255, null=True)),
                ('video_card', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_laptop_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMainAds',
            fields=[
                ('main_ads_id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_run_days', models.IntegerField()),
                ('ad_title', models.CharField(max_length=255)),
                ('added_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('expired', models.TextField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('featured', models.TextField()),
                ('price', models.BigIntegerField()),
                ('price_negotiable', models.CharField(blank=True, max_length=255, null=True)),
                ('view_count', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_main_ads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblModels',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_models',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMonitorSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_monitor_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMotocycleSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchal', models.CharField(blank=True, max_length=255, null=True)),
                ('engine', models.IntegerField()),
                ('features', models.TextField(blank=True, null=True)),
                ('kilometers', models.IntegerField()),
                ('lot_no', models.IntegerField()),
                ('make_year', models.IntegerField()),
                ('mileage', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_motocycle_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNetworkingEquipmentSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_networking_equipment_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_pictures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPrinterSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_printer_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblQuestions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('asked_on', models.DateField(blank=True, null=True)),
                ('question_comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblRealestateSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_road', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('bathroom', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('built_up', models.IntegerField()),
                ('features', models.TextField(blank=True, null=True)),
                ('floors', models.IntegerField()),
                ('furnishing', models.CharField(blank=True, max_length=255, null=True)),
                ('land_size', models.IntegerField()),
                ('livingroom', models.IntegerField()),
                ('property_location', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(blank=True, max_length=255, null=True)),
                ('water_supply', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_realestate_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblReplies',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('replied', models.TextField()),
                ('reply_comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_replies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblShoesSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_shoes_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSoftwareSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_software_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSportSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=255, null=True)),
                ('gear', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('wheel_size', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_sport_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblStorageSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_storage_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSubCategories',
            fields=[
                ('sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_sub_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTabletSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(blank=True, max_length=255, null=True)),
                ('connectivity', models.CharField(blank=True, max_length=255, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('internal_storage', models.IntegerField()),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('ram', models.CharField(blank=True, max_length=255, null=True)),
                ('screen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_tablet_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTravelSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('inclusion', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_travel_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUserRoles',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_user_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUsers',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('enabled', models.TextField()),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblWarranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_includes', models.CharField(blank=True, max_length=255, null=True)),
                ('warranty_period', models.CharField(blank=True, max_length=255, null=True)),
                ('warranty_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_warranty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblWishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tbl_wishlist',
                'managed': False,
            },
        ),
    ]
